const ShopActionTypes = {
    // UPDATE_COLLECTIONS : 'UPDATE_COLLECTIONS'
    FETCH_COLLECTIONS_START : 'FETCH_COLLECTIONS_START', //*This is when the first api call to our firestore begins
    FETCH_COLLECTIONS_SUCCESS : 'FETCH_COLLECTIONS_SUCCESS',
    FETCH_COLLECTIONS_FAILURE : 'FETCH_COLLECTIONS_FAILURE'
} 

export default ShopActionTypes